### ISSUE TITLE
unable to build on RPI3 with gcc v9.2

### ISSUE THREAD

**Issue by grkblood13** [AndyA/ts-split#1]
Various errors trying to build this. I realize it's quite old, but I'm hoping maybe someone could bring this up to date. Output from make is as follows:

[alarm@alarmpi ts-split]$ make
make  all-recursive
make[1]: Entering directory '/home/alarm/ts-split'
Making all in src
make[2]: Entering directory '/home/alarm/ts-split/src'
gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Werror -Wno-deprecated-declarations -g -O2 -MT tssplit.o -MD -MP -MF .deps/tssplit.Tpo -c -o tssplit.o tssplit.c
tssplit.c: In function 'set_input_file':
tssplit.c:131:3: error: unknown type name 'AVFormatParameters'; did you mean 'AVCodecParameters'?
  131 |   AVFormatParameters params, *ap = &params;
      |   ^~~~~~~~~~~~~~~~~~
      |   AVCodecParameters
tssplit.c:141:5: error: request for member 'prealloced_context' in something not a structure or union
  141 |   ap->prealloced_context = 1;
      |     ^~
tssplit.c:142:5: error: request for member 'channel' in something not a structure or union
  142 |   ap->channel = 0;
      |     ^~
tssplit.c:143:5: error: request for member 'standard' in something not a structure or union
  143 |   ap->standard = NULL;
      |     ^~
tssplit.c:145:24: error: 'CODEC_ID_NONE' undeclared (first use in this function); did you mean 'AV_CODEC_ID_NONE'?
  145 |   ic->video_codec_id = CODEC_ID_NONE;
      |                        ^~~~~~~~~~~~~
      |                        AV_CODEC_ID_NONE
tssplit.c:145:24: note: each undeclared identifier is reported only once for each function it appears in
tssplit.c:150:8: error: implicit declaration of function 'av_open_input_file'; did you mean 'set_input_file'? [-Werror=implicit-function-declaration]
  150 |   if ( av_open_input_file( &ic, name, fmt, 0, ap ) < 0 ) {
      |        ^~~~~~~~~~~~~~~~~~
      |        set_input_file
tssplit.c:154:5: error: 'AVFormatContext' {aka 'struct AVFormatContext'} has no member named 'loop_input'
  154 |   ic->loop_input = 0;
      |     ^~
tssplit.c:156:9: error: implicit declaration of function 'av_find_stream_info'; did you mean 'avformat_find_stream_info'? [-Werror=implicit-function-declaration]
  156 |   ret = av_find_stream_info( ic );
      |         ^~~~~~~~~~~~~~~~~~~
      |         avformat_find_stream_info
tssplit.c:158:5: error: implicit declaration of function 'av_close_input_file'; did you mean 'set_input_file'? [-Werror=implicit-function-declaration]
  158 |     av_close_input_file( ic );
      |     ^~~~~~~~~~~~~~~~~~~
      |     set_input_file
tssplit.c: In function 'alloc_stream':
tssplit.c:173:18: error: implicit declaration of function 'av_new_stream' [-Werror=implicit-function-declaration]
  173 |   AVStream *ns = av_new_stream( s, id );
      |                  ^~~~~~~~~~~~~
tssplit.c:173:18: error: initialization of 'AVStream *' {aka 'struct AVStream *'} from 'int' makes pointer from integer without a cast [-Werror=int-conversion]
tssplit.c: In function 'new_stream':
tssplit.c:183:5: error: 'AVStream' {aka 'struct AVStream'} has no member named 'stream_copy'
  183 |   st->stream_copy = 1;
      |     ^~
tssplit.c: In function 'set_output_file':
tssplit.c:194:3: error: unknown type name 'AVFormatParameters'; did you mean 'AVCodecParameters'?
  194 |   AVFormatParameters params, *ap = &params;
      |   ^~~~~~~~~~~~~~~~~~
      |   AVCodecParameters
tssplit.c:223:5: error: 'AVFormatContext' {aka 'struct AVFormatContext'} has no member named 'timestamp'
  223 |   oc->timestamp = 0;
      |     ^~
tssplit.c:230:8: error: implicit declaration of function 'av_set_parameters' [-Werror=implicit-function-declaration]
  230 |   if ( av_set_parameters( oc, ap ) < 0 ) {
      |        ^~~~~~~~~~~~~~~~~
tssplit.c:234:5: error: 'AVFormatContext' {aka 'struct AVFormatContext'} has no member named 'preload'
  234 |   oc->preload = ( int ) ( mux_preload * AV_TIME_BASE );
      |     ^~
tssplit.c: In function 'set_output':
tssplit.c:302:5: error: implicit declaration of function 'av_metadata_copy' [-Werror=implicit-function-declaration]
  302 |     av_metadata_copy( &ost->st->metadata, ist->st->metadata,
      |     ^~~~~~~~~~~~~~~~
tssplit.c:303:23: error: 'AV_METADATA_DONT_OVERWRITE' undeclared (first use in this function); did you mean 'AV_DICT_DONT_OVERWRITE'?
  303 |                       AV_METADATA_DONT_OVERWRITE );
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                       AV_DICT_DONT_OVERWRITE
tssplit.c:325:58: error: 'CODEC_ID_MP3' undeclared (first use in this function); did you mean 'AV_CODEC_ID_MP3'?
  325 |       if ( codec->block_align == 1 && codec->codec_id == CODEC_ID_MP3 ) {
      |                                                          ^~~~~~~~~~~~
      |                                                          AV_CODEC_ID_MP3
tssplit.c:328:31: error: 'CODEC_ID_AC3' undeclared (first use in this function); did you mean 'AV_CODEC_ID_AC3'?
  328 |       if ( codec->codec_id == CODEC_ID_AC3 ) {
      |                               ^~~~~~~~~~~~
      |                               AV_CODEC_ID_AC3
tssplit.c: In function 'close_output':
tssplit.c:446:5: error: implicit declaration of function 'av_metadata_free' [-Werror=implicit-function-declaration]
  446 |     av_metadata_free( &out->file->streams[i]->metadata );
      |     ^~~~~~~~~~~~~~~~
tssplit.c: In function 'start_output':
tssplit.c:489:41: error: 'AV_METADATA_DONT_OVERWRITE' undeclared (first use in this function); did you mean 'AV_DICT_DONT_OVERWRITE'?
  489 |                     in->file->metadata, AV_METADATA_DONT_OVERWRITE );
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                         AV_DICT_DONT_OVERWRITE
tssplit.c:491:8: error: implicit declaration of function 'av_write_header'; did you mean 'av_write_trailer'? [-Werror=implicit-function-declaration]
  491 |   if ( av_write_header( out->file ) < 0 ) {
      |        ^~~~~~~~~~~~~~~
      |        av_write_trailer
tssplit.c: In function 'dump_packet':
tssplit.c:573:34: error: format '%d' expects argument of type 'int', but argument 3 has type 'int64_t' {aka 'const long long int'} [-Werror=format=]
  573 |   printf( "flags=%08x, duration=%d, pos=%lld, convergence_duration=%lld\n",
      |                                 ~^
      |                                  |
      |                                  int
      |                                 %lld
  574 |           p->flags, p->duration, ( long long ) p->pos,
      |                     ~~~~~~~~~~~   
      |                      |
      |                      int64_t {aka const long long int}
cc1: all warnings being treated as errors
make[2]: *** [Makefile:409: tssplit.o] Error 1
make[2]: Leaving directory '/home/alarm/ts-split/src'
make[1]: *** [Makefile:455: all-recursive] Error 1
make[1]: Leaving directory '/home/alarm/ts-split'
make: *** [Makefile:366: all] Error 2
